# Generated by Django 5.0.6 on 2024-07-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shareRes", "0002_restaurant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="restaurent_content",
            new_name="restaurant_content",
        ),
    ]
